import type { AchievementRule } from '../types';

export const ACHIEVEMENT_RULES: AchievementRule[] = [
  {
    id: 'first-topic',
    name: 'Erste Schritte',
    description: 'Schließe dein erstes Topic ab.',
    icon: '🚀',
    trigger: { type: 'topic_completed' },
    condition: { aggregate: 'count', threshold: 1 },
    xpReward: 50,
  },
  {
    id: 'five-topics',
    name: 'Fünf-Sterne-Start',
    description: 'Schließe 5 Topics ab.',
    icon: '⭐',
    trigger: { type: 'topic_completed' },
    condition: { aggregate: 'count', threshold: 5 },
    xpReward: 100,
  },
  {
    id: 'perfectionist',
    name: 'Perfektionist',
    description: 'Schließe 5 Quizze mit 100% ab.',
    icon: '💯',
    trigger: { type: 'quiz_completed' },
    condition: { aggregate: 'count', threshold: 5, filterField: 'score', filterValue: 100 },
    xpReward: 150,
  },
  {
    id: 'module-master',
    name: 'Modulmeister',
    description: 'Schließe 8 Topics in einem Modul ab.',
    icon: '🎓',
    trigger: { type: 'topic_completed' },
    condition: { aggregate: 'count_distinct', field: 'topicId', scope: 'per_module', threshold: 8 },
    xpReward: 200,
  },
  {
    id: 'week-warrior',
    name: 'Wochenkrieger',
    description: '7 Tage in Folge gelernt.',
    icon: '🔥',
    trigger: { type: 'any' },
    condition: { aggregate: 'consecutive_days', threshold: 7 },
    xpReward: 200,
  },
  {
    id: 'iron-discipline',
    name: 'Eisendisziplin',
    description: '30 Tage in Folge gelernt.',
    icon: '🏆',
    trigger: { type: 'any' },
    condition: { aggregate: 'consecutive_days', threshold: 30 },
    xpReward: 500,
  },
  {
    id: 'quiz-marathon',
    name: 'Quiz-Marathonläufer',
    description: 'Schließe 20 Quizze ab.',
    icon: '🏃',
    trigger: { type: 'quiz_completed' },
    condition: { aggregate: 'count', threshold: 20 },
    xpReward: 150,
  },
  {
    id: 'early-bird',
    name: 'Frühaufsteher',
    description: '5 Aktivitäten vor 8:00 Uhr morgens.',
    icon: '🌅',
    trigger: { type: 'any' },
    condition: { aggregate: 'time_of_day', hourMin: 0, hourMax: 8, threshold: 5 },
    xpReward: 75,
  },
  {
    id: 'night-owl',
    name: 'Nachteule',
    description: '5 Aktivitäten nach 22:00 Uhr.',
    icon: '🦉',
    trigger: { type: 'any' },
    condition: { aggregate: 'time_of_day', hourMin: 22, hourMax: 24, threshold: 5 },
    xpReward: 75,
  },
  {
    id: 'passed-10',
    name: 'Bestanden!',
    description: '10 Quizze bestanden.',
    icon: '✅',
    trigger: { type: 'quiz_completed' },
    condition: { aggregate: 'count', threshold: 10, filterField: 'passed', filterValue: true },
    xpReward: 125,
  },
  {
    id: 'world-traveler',
    name: 'Weltenbummler',
    description: 'Topics in 2 verschiedenen Modulen abgeschlossen.',
    icon: '🌍',
    trigger: { type: 'topic_completed' },
    condition: { aggregate: 'count_distinct', field: 'moduleId', threshold: 2 },
    xpReward: 100,
  },
  {
    id: 'bridge-builder',
    name: 'Brückenbauer',
    description: 'Verbinde Konzepte aus CCNA und Azure durch Cross-References.',
    icon: '🌉',
    trigger: { type: 'topic_completed' },
    condition: { aggregate: 'count_distinct', field: 'moduleId', threshold: 2, useCrossReferences: true },
    xpReward: 200,
    secret: true,
  },
  {
    id: 'subnetting-hero',
    name: 'Subnetting-Held',
    description: 'Schließe alle Subnetting-Übungen ab.',
    icon: '🔢',
    trigger: { type: 'exercise_completed' },
    condition: { aggregate: 'all_in_set', set: ['subnetting-ex-1', 'subnetting-ex-2', 'subnetting-ex-3'] },
    xpReward: 150,
  },
  {
    id: 'diligent-bee',
    name: 'Fleißige Biene',
    description: '50 Fragen korrekt beantwortet.',
    icon: '🐝',
    trigger: { type: 'question_answered' },
    condition: { aggregate: 'count', threshold: 50, filterField: 'correct', filterValue: true },
    xpReward: 100,
  },
  {
    id: 'first-step-distinct',
    name: 'Erster Schritt',
    description: 'Schließe dein erstes distinct Topic ab.',
    icon: '👣',
    trigger: { type: 'topic_completed' },
    condition: { aggregate: 'count_distinct', field: 'topicId', threshold: 1 },
    xpReward: 25,
  },
];
