apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-training-canvas
  namespace: apps
spec:
  ingressClassName: traefik
  rules:
    - host: ccna.ajti.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: it-training-canvas
                port:
                  number: 80
